### ISSUE TITLE
Install of 5.2 failed!

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [austinkregel/laravel-auth-login#3]
Added kregel/auth-login to composer.json, when I ran the update I got this error:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Fatal error: Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found
```

**Comment by austinkregel** [comment]
Okay I think I fixed it, give it another try. If it doesn't work, truncate your `storage/logs/laravel.log` and then rerun the command. Once it fails again post the stack trace here. :)

**Comment by austinkregel** [comment]
Also, I just update packagist, so definitely try again. Hopefully that fixes it.

**Comment by ThamanVelasquezBice** [comment]
It installed, but now it says that the views are missing!

```
View [auth.login] not found.
```

**Comment by austinkregel** [comment]
Thanks I've fixed a majority of what I think was causing the issues, clear out your published views and config, then `composer update` and `php artisan vendor:publish --provider="Kregel\AuthLogin\AuthLoginServiceProvider"` and it should work just fine :)
